package dynobjx.com.jrs.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BRANCH.
 */
public class Branch {

    private Long id;
    private Integer branchId;
    private String branchName;
    private String branchAddress;
    private String contactPerson;
    private String contactNumbers;
    private Double longitude;
    private Double latitude;

    public Branch() {
    }

    public Branch(Long id) {
        this.id = id;
    }

    public Branch(Long id, Integer branchId, String branchName, String branchAddress, String contactPerson, String contactNumbers, Double longitude, Double latitude) {
        this.id = id;
        this.branchId = branchId;
        this.branchName = branchName;
        this.branchAddress = branchAddress;
        this.contactPerson = contactPerson;
        this.contactNumbers = contactNumbers;
        this.longitude = longitude;
        this.latitude = latitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getBranchId() {
        return branchId;
    }

    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    public String getBranchName() {
        return branchName;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    public String getBranchAddress() {
        return branchAddress;
    }

    public void setBranchAddress(String branchAddress) {
        this.branchAddress = branchAddress;
    }

    public String getContactPerson() {
        return contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    public String getContactNumbers() {
        return contactNumbers;
    }

    public void setContactNumbers(String contactNumbers) {
        this.contactNumbers = contactNumbers;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

}
