package dynobjx.com.jrs.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BRANCH_DETAIL.
 */
public class BranchDetail {

    private Long id;
    private Integer detailId;
    private String fullAddress;
    private String contactNumbers;
    private String managers;
    private String image;
    private String email;
    private Integer branchId;

    public BranchDetail() {
    }

    public BranchDetail(Long id) {
        this.id = id;
    }

    public BranchDetail(Long id, Integer detailId, String fullAddress, String contactNumbers, String managers, String image, String email, Integer branchId) {
        this.id = id;
        this.detailId = detailId;
        this.fullAddress = fullAddress;
        this.contactNumbers = contactNumbers;
        this.managers = managers;
        this.image = image;
        this.email = email;
        this.branchId = branchId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDetailId() {
        return detailId;
    }

    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    public String getFullAddress() {
        return fullAddress;
    }

    public void setFullAddress(String fullAddress) {
        this.fullAddress = fullAddress;
    }

    public String getContactNumbers() {
        return contactNumbers;
    }

    public void setContactNumbers(String contactNumbers) {
        this.contactNumbers = contactNumbers;
    }

    public String getManagers() {
        return managers;
    }

    public void setManagers(String managers) {
        this.managers = managers;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getBranchId() {
        return branchId;
    }

    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

}
