package dynobjx.com.jrs.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CITY.
 */
public class City {

    private Long id;
    private Integer cityId;
    private String cityName;
    private Integer provinceId;

    public City() {
    }

    public City(Long id) {
        this.id = id;
    }

    public City(Long id, Integer cityId, String cityName, Integer provinceId) {
        this.id = id;
        this.cityId = cityId;
        this.cityName = cityName;
        this.provinceId = provinceId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCityId() {
        return cityId;
    }

    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public Integer getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

}
