package dynobjx.com.jrs.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COUNTRY.
 */
public class Country {

    private Long id;
    private Integer countryId;
    private String countryName;

    public Country() {
    }

    public Country(Long id) {
        this.id = id;
    }

    public Country(Long id, Integer countryId, String countryName) {
        this.id = id;
        this.countryId = countryId;
        this.countryName = countryName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCountryId() {
        return countryId;
    }

    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    public String getCountryName() {
        return countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

}
