package dynobjx.com.jrs.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import dynobjx.com.jrs.dao.BranchDao;
import dynobjx.com.jrs.dao.ProvinceDao;
import dynobjx.com.jrs.dao.CityDao;
import dynobjx.com.jrs.dao.BarangayDao;
import dynobjx.com.jrs.dao.CountryDao;
import dynobjx.com.jrs.dao.UserInfoDao;
import dynobjx.com.jrs.dao.ServicesDao;
import dynobjx.com.jrs.dao.DestinationDao;
import dynobjx.com.jrs.dao.ServiceDefinitionDao;
import dynobjx.com.jrs.dao.ServiceDestinationDao;
import dynobjx.com.jrs.dao.BranchDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        BranchDao.createTable(db, ifNotExists);
        ProvinceDao.createTable(db, ifNotExists);
        CityDao.createTable(db, ifNotExists);
        BarangayDao.createTable(db, ifNotExists);
        CountryDao.createTable(db, ifNotExists);
        UserInfoDao.createTable(db, ifNotExists);
        ServicesDao.createTable(db, ifNotExists);
        DestinationDao.createTable(db, ifNotExists);
        ServiceDefinitionDao.createTable(db, ifNotExists);
        ServiceDestinationDao.createTable(db, ifNotExists);
        BranchDetailDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        BranchDao.dropTable(db, ifExists);
        ProvinceDao.dropTable(db, ifExists);
        CityDao.dropTable(db, ifExists);
        BarangayDao.dropTable(db, ifExists);
        CountryDao.dropTable(db, ifExists);
        UserInfoDao.dropTable(db, ifExists);
        ServicesDao.dropTable(db, ifExists);
        DestinationDao.dropTable(db, ifExists);
        ServiceDefinitionDao.dropTable(db, ifExists);
        ServiceDestinationDao.dropTable(db, ifExists);
        BranchDetailDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(BranchDao.class);
        registerDaoClass(ProvinceDao.class);
        registerDaoClass(CityDao.class);
        registerDaoClass(BarangayDao.class);
        registerDaoClass(CountryDao.class);
        registerDaoClass(UserInfoDao.class);
        registerDaoClass(ServicesDao.class);
        registerDaoClass(DestinationDao.class);
        registerDaoClass(ServiceDefinitionDao.class);
        registerDaoClass(ServiceDestinationDao.class);
        registerDaoClass(BranchDetailDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
