package dynobjx.com.jrs.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import dynobjx.com.jrs.dao.Branch;
import dynobjx.com.jrs.dao.Province;
import dynobjx.com.jrs.dao.City;
import dynobjx.com.jrs.dao.Barangay;
import dynobjx.com.jrs.dao.Country;
import dynobjx.com.jrs.dao.UserInfo;
import dynobjx.com.jrs.dao.Services;
import dynobjx.com.jrs.dao.Destination;
import dynobjx.com.jrs.dao.ServiceDefinition;
import dynobjx.com.jrs.dao.ServiceDestination;
import dynobjx.com.jrs.dao.BranchDetail;

import dynobjx.com.jrs.dao.BranchDao;
import dynobjx.com.jrs.dao.ProvinceDao;
import dynobjx.com.jrs.dao.CityDao;
import dynobjx.com.jrs.dao.BarangayDao;
import dynobjx.com.jrs.dao.CountryDao;
import dynobjx.com.jrs.dao.UserInfoDao;
import dynobjx.com.jrs.dao.ServicesDao;
import dynobjx.com.jrs.dao.DestinationDao;
import dynobjx.com.jrs.dao.ServiceDefinitionDao;
import dynobjx.com.jrs.dao.ServiceDestinationDao;
import dynobjx.com.jrs.dao.BranchDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig branchDaoConfig;
    private final DaoConfig provinceDaoConfig;
    private final DaoConfig cityDaoConfig;
    private final DaoConfig barangayDaoConfig;
    private final DaoConfig countryDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig servicesDaoConfig;
    private final DaoConfig destinationDaoConfig;
    private final DaoConfig serviceDefinitionDaoConfig;
    private final DaoConfig serviceDestinationDaoConfig;
    private final DaoConfig branchDetailDaoConfig;
    private final BranchDao branchDao;
    private final ProvinceDao provinceDao;
    private final CityDao cityDao;
    private final BarangayDao barangayDao;
    private final CountryDao countryDao;
    private final UserInfoDao userInfoDao;
    private final ServicesDao servicesDao;
    private final DestinationDao destinationDao;
    private final ServiceDefinitionDao serviceDefinitionDao;
    private final ServiceDestinationDao serviceDestinationDao;
    private final BranchDetailDao branchDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        branchDaoConfig = daoConfigMap.get(BranchDao.class).clone();
        branchDaoConfig.initIdentityScope(type);

        provinceDaoConfig = daoConfigMap.get(ProvinceDao.class).clone();
        provinceDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        barangayDaoConfig = daoConfigMap.get(BarangayDao.class).clone();
        barangayDaoConfig.initIdentityScope(type);

        countryDaoConfig = daoConfigMap.get(CountryDao.class).clone();
        countryDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        servicesDaoConfig = daoConfigMap.get(ServicesDao.class).clone();
        servicesDaoConfig.initIdentityScope(type);

        destinationDaoConfig = daoConfigMap.get(DestinationDao.class).clone();
        destinationDaoConfig.initIdentityScope(type);

        serviceDefinitionDaoConfig = daoConfigMap.get(ServiceDefinitionDao.class).clone();
        serviceDefinitionDaoConfig.initIdentityScope(type);

        serviceDestinationDaoConfig = daoConfigMap.get(ServiceDestinationDao.class).clone();
        serviceDestinationDaoConfig.initIdentityScope(type);

        branchDetailDaoConfig = daoConfigMap.get(BranchDetailDao.class).clone();
        branchDetailDaoConfig.initIdentityScope(type);

        branchDao = new BranchDao(branchDaoConfig, this);
        provinceDao = new ProvinceDao(provinceDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);
        barangayDao = new BarangayDao(barangayDaoConfig, this);
        countryDao = new CountryDao(countryDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        servicesDao = new ServicesDao(servicesDaoConfig, this);
        destinationDao = new DestinationDao(destinationDaoConfig, this);
        serviceDefinitionDao = new ServiceDefinitionDao(serviceDefinitionDaoConfig, this);
        serviceDestinationDao = new ServiceDestinationDao(serviceDestinationDaoConfig, this);
        branchDetailDao = new BranchDetailDao(branchDetailDaoConfig, this);

        registerDao(Branch.class, branchDao);
        registerDao(Province.class, provinceDao);
        registerDao(City.class, cityDao);
        registerDao(Barangay.class, barangayDao);
        registerDao(Country.class, countryDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(Services.class, servicesDao);
        registerDao(Destination.class, destinationDao);
        registerDao(ServiceDefinition.class, serviceDefinitionDao);
        registerDao(ServiceDestination.class, serviceDestinationDao);
        registerDao(BranchDetail.class, branchDetailDao);
    }
    
    public void clear() {
        branchDaoConfig.getIdentityScope().clear();
        provinceDaoConfig.getIdentityScope().clear();
        cityDaoConfig.getIdentityScope().clear();
        barangayDaoConfig.getIdentityScope().clear();
        countryDaoConfig.getIdentityScope().clear();
        userInfoDaoConfig.getIdentityScope().clear();
        servicesDaoConfig.getIdentityScope().clear();
        destinationDaoConfig.getIdentityScope().clear();
        serviceDefinitionDaoConfig.getIdentityScope().clear();
        serviceDestinationDaoConfig.getIdentityScope().clear();
        branchDetailDaoConfig.getIdentityScope().clear();
    }

    public BranchDao getBranchDao() {
        return branchDao;
    }

    public ProvinceDao getProvinceDao() {
        return provinceDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public BarangayDao getBarangayDao() {
        return barangayDao;
    }

    public CountryDao getCountryDao() {
        return countryDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public ServicesDao getServicesDao() {
        return servicesDao;
    }

    public DestinationDao getDestinationDao() {
        return destinationDao;
    }

    public ServiceDefinitionDao getServiceDefinitionDao() {
        return serviceDefinitionDao;
    }

    public ServiceDestinationDao getServiceDestinationDao() {
        return serviceDestinationDao;
    }

    public BranchDetailDao getBranchDetailDao() {
        return branchDetailDao;
    }

}
