package dynobjx.com.jrs.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROVINCE.
 */
public class Province {

    private Long id;
    private Integer provinceId;
    private String provinceName;

    public Province() {
    }

    public Province(Long id) {
        this.id = id;
    }

    public Province(Long id, Integer provinceId, String provinceName) {
        this.id = id;
        this.provinceId = provinceId;
        this.provinceName = provinceName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    public String getProvinceName() {
        return provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

}
