package dynobjx.com.jrs.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SERVICE_DESTINATION.
 */
public class ServiceDestination {

    private Long id;
    private Integer destinationTypeId;

    public ServiceDestination() {
    }

    public ServiceDestination(Long id) {
        this.id = id;
    }

    public ServiceDestination(Long id, Integer destinationTypeId) {
        this.id = id;
        this.destinationTypeId = destinationTypeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDestinationTypeId() {
        return destinationTypeId;
    }

    public void setDestinationTypeId(Integer destinationTypeId) {
        this.destinationTypeId = destinationTypeId;
    }

}
