package dynobjx.com.jrs.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SERVICES.
 */
public class Services {

    private Long id;
    private Integer serviceId;
    private String serviceName;
    private String remarks;
    private String metricSystem;
    private String imageFile;

    public Services() {
    }

    public Services(Long id) {
        this.id = id;
    }

    public Services(Long id, Integer serviceId, String serviceName, String remarks, String metricSystem, String imageFile) {
        this.id = id;
        this.serviceId = serviceId;
        this.serviceName = serviceName;
        this.remarks = remarks;
        this.metricSystem = metricSystem;
        this.imageFile = imageFile;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getServiceId() {
        return serviceId;
    }

    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    public String getServiceName() {
        return serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getMetricSystem() {
        return metricSystem;
    }

    public void setMetricSystem(String metricSystem) {
        this.metricSystem = metricSystem;
    }

    public String getImageFile() {
        return imageFile;
    }

    public void setImageFile(String imageFile) {
        this.imageFile = imageFile;
    }

}
